[project]
name = "masterthesis"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "arviz>=0.21,<1",
    "causalpy>=0.8.1",
    "matplotlib>=3.11.1",
    "numpy<2.4",
    "pandas>=3.0.5",
    "pymc>=5.28.1,<5.29",
    "pymc-extras>=0.10,<0.11",
    "ruptures>=1.1.10",
    "scikit-learn>=1.9.0",
    "scipy-stubs~=1.18.0",
    "statsmodels>=0.14.6",
]
